In [3]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [22]:
python_list = [1,2,3,4,5]
arr = np.array(python_list)
arr

array([1, 2, 3, 4, 5])

In [4]:
arr =np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [6]:
np.zeros((5,3) )

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [0]:
np.zeros((4,3),dtype = "int") #int deyr jonno sob int dekabe

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [0]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [0]:
np.ones((5))

array([1., 1., 1., 1., 1.])

In [0]:
np.full((4,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [0]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [0]:
np.eye((4), dtype="int")

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [0]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [0]:
np.diag([4,5,6])

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [0]:
np.random.rand(3,4)

array([[0.23486019, 0.98602646, 0.40975765, 0.29626861],
       [0.99931411, 0.85773941, 0.68348114, 0.99006014],
       [0.30579551, 0.02925265, 0.90375352, 0.74799077]])

In [0]:
np.random.rand(2,2,2)

array([[[0.76167701, 0.95702325],
        [0.21995955, 0.59072886]],

       [[0.87989989, 0.69347254],
        [0.03986532, 0.13985023]]])

In [0]:
np.random.randn(2,3)

array([[ 0.01291941, -2.92441653, -0.28092273],
       [ 0.61996856, -0.96731852,  0.40155828]])

In [0]:
np.random.randint(0,10,10)


array([8, 7, 9, 2, 3, 7, 7, 6, 9, 8])

***Attribute***

In [0]:
arr =np.random.randint(0,10,(4,3))


In [10]:
print (arr)
arr.reshape(6,2)

[[8 1 5]
 [6 3 0]
 [0 6 3]
 [0 4 2]]


array([[8, 1],
       [5, 6],
       [3, 0],
       [0, 6],
       [3, 0],
       [4, 2]])

In [11]:
arr= np.random.randint(0,25,(4,3))
print (arr)
print(arr.max())
print(arr.argmax())

[[21 16 14]
 [17 10 18]
 [20 17 19]
 [18  1 19]]
21
0


In [12]:
arr.shape

(4, 3)

In [13]:
arr.ndim

2

In [14]:
arr.size

12

In [15]:
arr.dtype

dtype('int64')

In [0]:
arr.itemsize

8

In [16]:
arr2 = arr

print(arr.data)
print(arr2.data)

new

In [17]:
sample_arr = np.random.randint(0,100,10)

sample_arr

array([60, 80, 93,  4, 70, 33, 93, 50, 17, 37])

In [18]:
sample_arr[3]

4

In [19]:
for i in range(len(sample_arr)):
  print(sample_arr[i])

60
80
93
4
70
33
93
50
17
37


In [0]:
print(sample_arr)
sample_arr[1:6]


[67 96 96 18  6 19  1 60 66 81]


array([96, 96, 18,  6, 19])

In [0]:
arr = sample_arr[5:]

arr[:3] = 100

sample_arr

array([ 67,  96,  96,  18,   6, 100, 100, 100,  66,  81])

In [0]:
arr=sample_arr.copy()
arr[:]=1000
print(sample_arr)
print(arr)

[ 67  96  96  18   6 100 100 100  66  81]
[1000 1000 1000 1000 1000 1000 1000 1000 1000 1000]


In [20]:
arr2d=np.random.randint(0,100,(5,5))
print(arr2d)
arr2d[1][2]

[[61 51 15 44 50]
 [62 76  0 16 30]
 [26 35 72 20 56]
 [62 99 93 29 16]
 [38  0 38 72 66]]


0

In [21]:
arr2d[3,2]

93