**Array**

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [2]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np
arr= np.array([[[1,2,3,4],[5,6,7,8],[6,8,9,10]]])
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 6  8  9 10]]]


## Dimension ....its tell us how many dimension the arrays *have* bold text

In [4]:
import numpy as np

a= np.array(42)
b= np.array([1,2,3,4,5])
c= np.array([[1,2,3],[4,5,6],[2,5,4]])
d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


high dimensio


In [5]:
import numpy as np
arr=np.array([1,2,3,4],ndmin =4)
print(arr)
print('number of dimensions:',arr.ndim)

[[[[1 2 3 4]]]]
number of dimensions: 4


## **numpy array elements**

In [6]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[0])

1


In [7]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[1])

2


In [8]:
import numpy as np
arr= np.array([1,2,3,4,5,6])
print(arr[2]+arr[3])

7


2nd element on 1st dim

In [9]:
import numpy as np

arr=np.array([[1,2,3,4,],[5,6,7,8]])
print('2nd element on 1st dim:',arr[0,1])

2nd element on 1st dim: 2


In [10]:
import numpy as np

arr=np.array([[1,2,3,4,5],[9,6,7,8,10]])
print(arr[1,3])

8


# Access 3 d

In [11]:
import numpy as np
arr=np.array([[[1,2,3,],[4,5,6]],[[7,8,9],[11,22,33]]])
print(arr[0,1,2])

6


# negetive indexing

In [12]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,-1])

10


# **Numpy array Slicing** eita start:end:

In [13]:
import numpy as np
arr= np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [14]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[4:])

[5 6 7 8]


In [15]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[:4])

[1 2 3 4]


# negetive slicing

In [16]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[-3:-1])

[6 7]


### step

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[::2])

# 2_D slicing Arrays

In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

# **DATa types checking the data type

**

In [ ]:
import numpy as np
arr= np.array([1,2,4])
print(arr.dtype)

In [ ]:
import numpy as np
arr=np.array(['apple','banana','cherry'])
print(arr.dtype)

# Define data type

In [ ]:
import numpy as np
arr= np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)

In [ ]:
import numpy as np #4 byte integer
arr=np.array([1,2,3,4],dtype='i4')
print(arr)
print(arr.dtype)

In [ ]:
import numpy as np
arr= np.array([1.1,2.1,3.1])
newarr=arr.astype('i')

print(newarr)
print(newarr.dtype)

# Numpy array copy to view

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42

print(arr)
print(x)

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
y=arr.view()

print(x.base)
print(y.base)

## Array Shape

In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)  #2,4 means that the array has 2 dimension and the dimension has 4 elements

In [ ]:
import numpy as np

arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('shape of array :', arr. shape)

Array reshape


In [ ]:
# 1D to 2D
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3) 
print(newarr)

In [ ]:
1D to 3D
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

In [ ]:
import numpy as np
arr= np.array([1,2,3,4,5,6,7,8])
print (arr.reshape(2,4).base)

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
newarr=arr.reshape(-1)
print(newarr)

## **Numpy arrray Iterating**

In [ ]:
#1D array
import numpy as np
arr=np.array([1,2,3])
for x in arr:
  print(x)

In [ ]:
#2D array
import numpy as np
arr= np.array([[1,2,3],[4,5,6]])
for x in arr:
  print (x)

In [ ]:
import numpy as np
arr= np.array([[1,2,3],[4,5,6]])
for x in arr:
  for y in x:
    print(y)

In [ ]:
#3D Arrays
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
for x in arr:
 print (x)

In [ ]:
#itearte it 
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
for x in arr:
  for y in x:
    for z in y:
     # print(z)
       

# Iterating as nditer()

In [ ]:
import numpy as np
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in np.nditer(arr):
  print(x)

In [ ]:
#array as string
import numpy as np
arr=np.array([1,2,3])
for x in np.nditer(arr,flags=['buffered'],op_dtypes=['S']):
  print(x)

In [ ]:
#2D array scalar the 2D array skipping 1 elements
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[:,::2]):
  print (x)

In [ ]:
import numpy as np
arr=np.array([1,2,3])
for idx,x in np.ndenumerate(arr):
  print(idx,x)

In [ ]:
#2D arryas 
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
for idx,x in np.ndenumerate(arr):
  print(idx,x)

## Numpy joning array

In [ ]:
#join two array
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

In [ ]:
#join two 2D arrays along rows(axis=1)
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

In [ ]:
#joining array using stack function
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.stack((arr1,arr2),axis=1)
print(arr)

In [ ]:
#hstack
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.hstack((arr1,arr2))
print(arr)

In [ ]:
#vstack
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.vstack((arr1,arr2))
print(arr)

In [ ]:
#dstack
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.dstack((arr1,arr2))
print(arr)

## **Numpy splitting Array**

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,4)
print(newarr)

In [ ]:
#another way
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

In [ ]:
#splitting 2D array in to threee 2D arrays
import numpy as np
arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr=np.array_split(arr,3)
print(newarr)

In [ ]:
#splitting 2D array in to threee 2D arrays
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr=np.array_split(arr,3)
print(newarr)

In [ ]:
#splitting 2D array in to threee 2D arrays(axis=1)
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr=np.array_split(arr,3,axis=1)
print(newarr)

In [ ]:
#hsplit
import numpy as np
arr= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr=np.hsplit(arr,3)
print(newarr)

### **searching array**

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,4,4])
x=np.where(arr==4)
print(x)

In [ ]:
#find even
import numpy as np
arr=np.array([1,2,3,4,5,7,8,9])
x=np.where(arr%2==0)
print(x)

In [ ]:
#find odd
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
x=np.where(arr%2==1)
print(x)

In [ ]:
#search sorted
import numpy as np
arr=np.array([6,7,8,9])
x=np.searchsorted(arr,7)
print(x)

In [ ]:
#search right side sorted
import numpy as np
arr=np.array([6,7,8,9])
x=np.searchsorted(arr,7,side='right')
print(x)

In [ ]:
#multiple value
import numpy as np
arr=np.array([1,3,5,7])
x=np.searchsorted(arr,[2,4,6])
print(x)

In [ ]:
import numpy as np
arr=np.array([3,2,0,1])
print(np.sort(arr))

In [ ]:
import numpy as np
arr= np .array(['banana','cherry','apple'])
print(np.sort(arr))

In [ ]:
#2D array
import numpy as np
arr= np.array([[3,2,1],[5,0,1]])
print(np.sort(arr))

## **Filtering Array**

In [ ]:
import numpy as np
arr=np.array([41,42,43,44])
x=[True,False,True,False]
newarr=arr[x]
print(newarr)
#its retur 41,43 because the new filter contains only the values where the filter
#array had the value true.in this case ,index 0 and 2

In [ ]:
#creating the filter array
import numpy as np
arr=np.array([41,42,43,44])
#create an empty list
filter_arr=[]
#go through each slement in arr
for element in arr:
  #if the element is higher then 42,set the value true or flase
  if element > 42:
    filter_arr.append(True)
  else:
   filter_arr.append(False)
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

In [ ]:
#return only even
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
#create an empty list
filter_arr=[]
#go through each slement in arr
for element in arr:
  #if the element is completely divisional by 2,set the value true or flase
  if element%2==0:
    filter_arr.append(True)
  else:
   filter_arr.append(False)
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

In [ ]:
#higher than 42
import numpy as np
arr=np.array([41,42,43,44])
filter_arr=arr>42
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

In [ ]:
import numpy as np
arr= np.array([1,2,3,4,5,6,7,])
filter_arr=arr%2==0
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

## ***Random NUmbers in numpy***

In [ ]:
#generate a random integer from 0 to 100
from numpy import random
x=random.randint(100)
print(x)

In [ ]:
#rand()
from numpy import random
x=random.rand()
print(x)

In [ ]:
#randint
from numpy import random
x=random.randint(100,size=(5))
print(x)

In [ ]:
from numpy import random
x=random.randint(100,size=(3,5))
print(x)

In [ ]:
#float (rand)
from numpy import random
x=random.rand(5)
print(x)

In [ ]:
from numpy import random
x=random.rand(3,5)
print(x)

choice

In [ ]:
from numpy import random
x=random.choice([3,5,7,9])
print(x)

In [ ]:
from numpy import random
x=random.choice([3,5,7,9],size=(3,5))
print(x)

Data Distribution


In [ ]:
from numpy import random
x=random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0],size=(100))
print(x)

In [ ]:
from numpy import random
x=random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0],size=(3,5))
print(x)

In [ ]:
#Random permutations
from numpy import random
import numpy as np
arr=np.array([1,2,3,4,5])
random.shuffle(arr)
print(arr)

In [ ]:
from numpy import random
import numpy as np
arr=np.array([1,2,3,4,5])
print(random.permutation(arr))

seaborn


In [ ]:
import matplotlib.pyplot as plt

In [ ]:
import seaborn as sns

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
sns . distplot([0,1,2,3,4,5,])
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
sns.distplot([0,1,2,3,4,5],hist= False)
plt.show()

normal gaussian

In [ ]:
#size= 2*3
from numpy import random
x=random.normal(size=(2,3))
print(x)

In [ ]:
from numpy import random
x=random.normal(loc=1,scale=2,size=(2,3))
print(x)

# **visualization**

In [ ]:
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns
sns.distplot(random.normal(size=1000),hist=False)
plt.show()

Binomial Distribution

In [ ]:
from numpy import random
x=random.binomial(n=10,p=0.5,size=10)
print(x)

In [ ]:
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns
sns.distplot(random.binomial(n=10,p=.5,size=1000),hist=True,kde=False)
plt.show()

In [ ]:
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns 
sns.distplot(random.normal(loc=50,scale=5,size=1000),hist=False,label='normal')
sns.distplot(random.binomial(n=100,p=.5,size=1000),hist=False,label='binomial')
plt.show()

poisson distribution

In [ ]:
from numpy import random
x=random.poisson(lam=2,size=10)
print(x)

In [ ]:
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns
sns.distplot(random.poisson(lam=2,size=1000),kde=False)
plt.show()

difference between normal and poisson

In [ ]:
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

sns.distplot(random.normal(loc=50, scale=7, size=1000), hist=False, label='normal')
sns.distplot(random.poisson(lam=50, size=1000), hist=False, label='poisson')

plt.show()

unifrom distribution

In [ ]:
#Create a 2x3 uniform distribution sample:
from numpy import random

x = random.uniform(size=(2, 3))

print(x)

In [ ]:
#Visualization of Uniform Distribution
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

sns.distplot(random.uniform(size=1000), hist=False)

plt.show()

# Logistic Distribution

In [ ]:
from numpy import random

x = random.logistic(loc=1, scale=2, size=(2, 3))

print(x)

In [ ]:
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

sns.distplot(random.logistic(size=1000), hist=False)

plt.show()

Difference Between Logistic and Normal Distribution

In [ ]:
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

sns.distplot(random.normal(scale=2, size=1000), hist=False, label='normal')
sns.distplot(random.logistic(size=1000), hist=False, label='logistic')

plt.show()

Multinomial Distribution


In [ ]:
from numpy import random

x = random.multinomial(n=6, pvals=[1/6, 1/6, 1/6, 1/6, 1/6, 1/6])

print(x)
#Multinomial samples will NOT produce a single value!
# They will produce one value for each pval.

# Exponential Distribution

In [ ]:
from numpy import random

x = random.exponential(scale=2, size=(2, 3))

print(x)


In [ ]:
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

sns.distplot(random.exponential(size=1000), hist=False)

plt.show()

# Chi Square Distribution

In [ ]:
from numpy import random

x = random.chisquare(df=2, size=(2, 3))

print(x)

In [ ]:
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

sns.distplot(random.chisquare(df=1, size=1000), hist=False)

plt.show()

# Rayleigh Distribution

In [ ]:
from numpy import random

x = random.rayleigh(scale=2, size=(2, 3))

print(x)

# Visualization

In [ ]:
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

sns.distplot(random.rayleigh(size=1000), hist=False)

plt.show()

# Pareto Distribution

In [ ]:
from numpy import random

x = random.pareto(a=2, size=(2, 3))

print(x)

In [ ]:
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

sns.distplot(random.pareto(a=2, size=1000), kde=False)

plt.show()

# Zipf Distribution

In [ ]:
from numpy import random

x = random.zipf(a=2, size=(2, 3))

print(x)

In [ ]:
#Sample 1000 points but plotting only ones with value < 10 for more meaningful chart.
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

x = random.zipf(a=2, size=1000)
sns.distplot(x[x<10], kde=False)

plt.show()

## NumPy ufuncs

Vectorization?
Converting iterative statements into a vector based operation is called vectorization.

It is faster as modern CPUs are optimized for such operations.

In [ ]:
#Without ufunc, we can use Python's built-in zip() method:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

In [ ]:
#With ufunc, we can use the add() function:
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)